# @format

name: GitHub Classroom Workflow

on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: 0 */1 * * *

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install pkg
        run: npm install
      - name: get csv to json
        uses: ./
      - name: build pages
        run: npm build
      - name: commit
        run: |
          git config user.name Jack-Zhang-1314
          git config user.email zyj17715640603@gmail.com
          git add .
          git commit -m "generated"
          git push origin gh-pages
